export type ThemeType = {
  name: string;
  "color-scheme": "light" | "dark";
  primary: string;
  secondary?: string;
  accent?: string;
  neutral?: string;
};

export const themes: ThemeType[] = [
  {
    name: "light",
    "color-scheme": "light",
    primary: "#570df8",
    secondary: "#f000b8",
    accent: "#37cdbe",
    neutral: "#1f2937",
  },
  {
    name: "dark",
    "color-scheme": "dark",
    primary: "#793ef9",
    secondary: "#f000b8",
    accent: "#37cdbe",
    neutral: "#a6adba",
  },
  {
    name: "cupcake",
    "color-scheme": "light",
    primary: "#65c3c8",
    secondary: "#ef9fbc",
    accent: "#eeaf3a",
    neutral: "#291334",
  },
  {
    name: "bumblebee",
    "color-scheme": "light",
    primary: "#e0a82e",
    secondary: "#f9d72f",
    accent: "#181830",
    neutral: "#ffffff",
  },
  {
    name: "emerald",
    "color-scheme": "light",
    primary: "#66cc8a",
    secondary: "#377cfb",
    accent: "#f471b5",
    neutral: "#333c4d",
  },
  {
    name: "corporate",
    "color-scheme": "light",
    primary: "#4b6bfb",
    secondary: "#7b92b2",
    accent: "#97d1a9",
    neutral: "#181a2a",
  },
  {
    name: "synthwave",
    "color-scheme": "dark",
    primary: "#e779c1",
    secondary: "#58c7f3",
    accent: "#f3cc30",
    neutral: "#793ef9",
  },
  {
    name: "retro",
    "color-scheme": "light",
    primary: "#ec4899",
    secondary: "#a4c1cf",
    accent: "#ef9995",
    neutral: "#7d7259",
  },
  {
    name: "cyberpunk",
    "color-scheme": "light",
    primary: "#ff7598",
    secondary: "#75d1f0",
    accent: "#c07eec",
    neutral: "#121212",
  },
  {
    name: "valentine",
    "color-scheme": "light",
    primary: "#e96d7b",
    secondary: "#a991f7",
    accent: "#8be8fd",
    neutral: "#552a3c",
  },
  {
    name: "halloween",
    "color-scheme": "dark",
    primary: "#f97316",
    secondary: "#8808e7",
    accent: "#34d399",
    neutral: "#a3a3a3",
  },
  {
    name: "garden",
    "color-scheme": "light",
    primary: "#ec4899",
    secondary: "#a78bfa",
    accent: "#5c9f67",
    neutral: "#253027",
  },
  {
    name: "forest",
    "color-scheme": "dark",
    primary: "#1eb854",
    secondary: "#1db9ac",
    accent: "#a9ee99",
    neutral: "#a6adba",
  },
  {
    name: "aqua",
    "color-scheme": "dark",
    primary: "#09ecf3",
    secondary: "#966fb3",
    accent: "#ffe999",
    neutral: "#bfd4fa",
  },
  {
    name: "lofi",
    "color-scheme": "light",
    primary: "#0d0d0d",
    secondary: "#1a1a1a",
    accent: "#262626",
    neutral: "#333333",
  },
  {
    name: "pastel",
    "color-scheme": "light",
    primary: "#d1c1d7",
    secondary: "#f6cbd1",
    accent: "#b4e9d6",
    neutral: "#a1a1aa",
  },
  {
    name: "fantasy",
    "color-scheme": "light",
    primary: "#793ef9",
    secondary: "#5e81ac",
    accent: "#ec8934",
    neutral: "#3c3c3c",
  },
  {
    name: "wireframe",
    "color-scheme": "light",
    primary: "#b8b8b8",
    secondary: "#b8b8b8",
    accent: "#b8b8b8",
    neutral: "#b8b8b8",
  },
  {
    name: "black",
    "color-scheme": "dark",
    primary: "#333333",
    secondary: "#4d4d4d",
    accent: "#666666",
    neutral: "#7f7f7f",
  },
  {
    name: "luxury",
    "color-scheme": "dark",
    primary: "#ffffff",
    secondary: "#4b5563",
    accent: "#a78bfa",
    neutral: "#dca54c",
  },
  {
    name: "dracula",
    "color-scheme": "dark",
    primary: "#ff79c6",
    secondary: "#bd93f9",
    accent: "#ffb86c",
    neutral: "#414558",
  },
  {
    name: "cmyk",
    "color-scheme": "light",
    primary: "#45aeee",
    secondary: "#e8488a",
    accent: "#f9cc33",
    neutral: "#1a1a1a",
  },
  {
    name: "autumn",
    "color-scheme": "light",
    primary: "#8c0327",
    secondary: "#d85251",
    accent: "#f39b75",
    neutral: "#7c5745",
  },
  {
    name: "business",
    "color-scheme": "dark",
    primary: "#1c4e80",
    secondary: "#ea6947",
    accent: "#20a4a4",
    neutral: "#a6adba",
  },
  {
    name: "acid",
    "color-scheme": "light",
    primary: "#ff00ff",
    secondary: "#ff7a00",
    accent: "#ccff00",
    neutral: "#3b0054",
  },
  {
    name: "lemonade",
    "color-scheme": "light",
    primary: "#519903",
    secondary: "#fcd229",
    accent: "#fff333",
    neutral: "#3a2d21",
  },
  {
    name: "night",
    "color-scheme": "dark",
    primary: "#3abff8",
    secondary: "#a37acc",
    accent: "#f471b5",
    neutral: "#a6adba",
  },
  {
    name: "coffee",
    "color-scheme": "dark",
    primary: "#c7926b",
    secondary: "#264653",
    accent: "#69a4a8",
    neutral: "#a6adba",
  },
  {
    name: "winter",
    "color-scheme": "light",
    primary: "#047aff",
    secondary: "#463aa1",
    accent: "#c149ad",
    neutral: "#0b132b",
  },
  {
    name: "dim",
    "color-scheme": "dark",
    primary: "#66cc8a",
    secondary: "#f471b5",
    accent: "#f9a8d4",
    neutral: "#a6adba",
  },
  {
    name: "nord",
    "color-scheme": "light",
    primary: "#5e81ac",
    secondary: "#81a1c1",
    accent: "#88c0d0",
    neutral: "#d8dee9",
  },
  {
    name: "sunset",
    "color-scheme": "dark",
    primary: "#ff7598",
    secondary: "#f471b5",
    accent: "#c07eec",
    neutral: "#a6adba",
  },
  {
    name: "caramellatte",
    "color-scheme": "light",
    primary: "#212121",
    secondary: "#755f4d",
    accent: "#a38e7e",
    neutral: "#c7b8aa",
  },
  {
    name: "abyss",
    "color-scheme": "dark",
    primary: "#53ff92",
    secondary: "#c59cff",
    accent: "#81f8c6",
    neutral: "#a6adba",
  },
  {
    name: "silk",
    "color-scheme": "light",
    primary: "#ffde59",
    secondary: "#3d4451",
    accent: "#57a9c7",
    neutral: "#ff8a35",
  },
];
